### ISSUE TITLE
Can not create item metadata config using openhab-js

### ISSUE THREAD

**Issue by jhuizingh** [openhab/openhab-js#108]
Although itemMetadata is included as an option on the `createItem` function, that value does not seem to be used if I am [reading this ](https://openhab.github.io/openhab-js/items_managed.js.html#line270) correctly.  

Additionally, there is a mismatch between the signatures for `addItem`, `createItem`, and `replaceItem`, although it seems like they all ultimately call `createItem` under the hood so it would be really nice if they had the same options. On a related note, it is not clear to me what the difference between `addItem` and `createItem` is or what it means to me when I am developing a script. 

## Expected Behavior

When creating an item using this library, I can configure any metadata I need. 

## Current Behavior

I am unable to create/configure metadata on an item. There is an ability to set the `value` of metadata, but i want to set the `config` of metadata.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: (e.g., openHAB and **JS Scripting add-on version**)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by florian-h05** [comment]
@jhuizingh, I will take a look at each of your points and update this comment according to my progress.

> Additionally, there is a mismatch between the signatures for addItem, createItem, and replaceItem, although it seems like they all ultimately call createItem …

Yes, they all ultimately call `createItem`. The mismatch in their params/signature is something I will correct as soon as I had a look at everything you mentioned.

> On a related note, it is not clear to me what the difference between addItem and createItem is or what it means to me when I am developing a script.

`createItem` creates a new Item object that is not registered with any provider and therefore not in the Item registry. That means, that `createItem` actually doesn‘t really create an openHAB Item, it only creates an Item object. Currently I have no use case for `createItem` in mind for developing a script. I think `createItem` is meant to be a private function the normal user should not see.

`addItem` adds the Item object that createItem returns to the registry, what makes it a real openHAB Item.


When you develop a script, you can ignore `createItem` and use `addItem` to add/create openHAB Items.

**Comment by jhuizingh** [comment]
Thank you, @florian-h05!
