### ISSUE TITLE
event data payload differs from UI to file-bases rules

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#111]
As already noticed in some PRs (https://github.com/openhab/openhab-js/pull/106, https://github.com/openhab/openhab-js/pull/110), the `event` object differs from UI-based to file-based rules.

In file-based rules the event data is "formatted" by [`getTriggeredData(input)`](https://github.com/openhab/openhab-js/blob/394fb9959ce92f57766d495fb98c298276d78615/rules/rules.js#L339).

A solution to unify the event object of both would be to simply expose the above mentioned function and to advise the user to add the following on top of his UI rules:

```javascript
if (typeof event !== 'undefined') event = require('openhab').rules.getTriggeredData(new Map().set('event', event));
```

Is there any way to put automatically add content to UI scripts?

WDYT @digitaldan @jpg0 ?

**Comment by jpg0** [comment]
Whilst that would technically work in this case, my fear is that due to there being different implementations triggering the rules, this is only a hack rather than a proper solution. It won't fix all differences (e.g. can you use const in UI rules yet?), and may also break if the current wrapping code changes.

As for whether it's possible to inject this transparently, sure, it's possible.

**Comment by florian-h05** [comment]
> my fear is that due to there being different implementations triggering the rules, this is only a hack rather than a proper solution.

So you would not advise to inject or add that to the top of MainUI scripts?

By the way, I found one more difference between UI and file based: UI based scripts do not reload on changes in `node_modules`.
You have to disable/enable them to reload dependencies.

**Comment by ssalonen** [comment]
Does the workaround in the first post work for thing status update triggers?

**Comment by florian-h05** [comment]
Closing as we won‘t fix this here as this is related to openHAB Core.
