### ISSUE TITLE
[JS Scripting] Directory permissions for $OPENHAB_CONF/automation/js

### ISSUE THREAD

**Issue by DavidR1953** [openhab/openhab-js#112]
## Expected Behavior
VS-Code users should be able to create files.

## Current Behavior
When the JavaScript Scripting add-on is installed it creates the directory $OPENHAB_CONF/automation/js with permissions 755
VSCode users of the default openhabian installed setup cannot write to this directory because the user is openhabian, not openhab.

## Possible Solution
Create the directory with 775 permissions
This will allow openhab group members write permissions.

## Steps to Reproduce (for Bugs)
1.
2.

## Your Environment

* Version used:  openHAB 3.3.0.M4 and JS Scripting add-on 3.3.0.M4
* Environment name and version : Java 11
* Operating System and version: Raspbian Buster on RPI4, openhabian

**Comment by digitaldan** [comment]
Hi David, this sounds like a ticket for https://github.com/openhab/openhab-addons .  This repo is simply the pure Javascript library that gets included the with JavaScript binding.

**Comment by DavidR1953** [comment]
My apologies. I'll move it there. Have to be tomorrow though. Thanks for
the heads up.

Warm regards,

David Read
