### ISSUE TITLE
.js files are not run / reload after change

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-js#130]
working with js on one instance of openhab, then aprepared new one, i installed jscripting addon from GUI, and npm i openhab from command line.

/etc/openhab/automation/js has few .js rules. i can add new files, changes existing ones and ther are not reloaded - they are not loaded even on openhab restart. Adding an EMCA script is working fine. 
Don't know what to do - i change my java engine to 
```
java --version
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode)
```

i tried uninstall and install the addon again, openhab-cli cleancache etc. 
any ideas?:)

**Comment by florian-h05** [comment]
Hello @JacekKac,
first of all, as this issue is related to the JS Scripting add-on and not to the openHAB JavaScript library (which is in this repo), this issue should be on the openhab-addons repo. Please remember the next time.

Can you tell me your openHAB version?

**Comment by JacekKac** [comment]
Sure thank you for this information,  it was not clear for me :) 
Version:     3.3.0.M5 (Build)

**Comment by florian-h05** [comment]
Hmm okay, my production system is also on 3.3.0.M5 but I have no problems.
I am using `openjdk 11.0.15 2022-04-19`.

**Comment by JacekKac** [comment]
reverting to java 
openjdk 11.0.15 2022-04-19 LTS
OpenJDK Runtime Environment Zulu11.56+19-CA (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.56+19-CA (build 11.0.15+10-LTS, mixed mode)
and it's working again

**Comment by florian-h05** [comment]
> and it's working again

Okay, great. I just wanted to write something regarding Java 17.

I am not sure how the compatibility with Java 17 currently is, but I think that I've read that there are still some issues with Java 17, so I would have recommended to revert back to Java 11.

As your problem is solved, I will close this issue now.
