### ISSUE TITLE
[triggers] How to skip parameter in trigger configuration

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-js#140]
https://openhab.github.io/openhab-js/triggers.html#.ItemStateChangeTrigger says:

> (static) ItemStateChangeTrigger(itemName, oldStateopt, newStateopt, triggerNameopt)

That is, the `oldState`, `newState` and `triggerName` parameters are optional.  Please document how to skip `oldState` and utilize only `newState`.

I want to crate a trigger, only based on the new state, irrespective of the old state.  The concrete case is, that I have broken inverter and sometimes it resets and produces `0 W`atts.  I want to trigger an event, when the watts are zero, irrespective of the previous state of the watts.

**Comment by florian-h05** [comment]
Hello @dilyanpalauzov,
you can skip parameters by passing in `null`, therefor for you case you could use:

```javascript
triggers.ItemStateChangeTrigger('itemname', null, 'ON');
```

**Comment by florian-h05** [comment]
I will update the docs to mention that.
