### ISSUE TITLE
JSRules creates UIDs with many leading dashes

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-js#141]
With openHAB 3.2 I create a JS-rule using:
```
rules.JSRule({
    name: 'Помпи промяна горна/долна граница',
    description: 'Помпи промяна горна/долна граница',
    triggers: [
        triggers.ItemStateChangeTrigger('pompi_on', null, null, "W1"),
        triggers.ItemStateChangeTrigger('pompi_off', null, null, "W2")
    ],
    execute: (data) => {
        execute()
    }
})
```
Then I call in Karaf:
```
openhab> openhab:automation listRules                                                                                                   
----------------------------------------------------------------------------------------------------
ID     UID                                 NAME                                STATUS         
----------------------------------------------------------------------------------------------------
1      ----------------------------------325106c4-0fc3-49f9-a466-a988921c6bff Помпи промяна горна/долна граница   IDLE           
```

The problem report is that the generated UID shall not contain many dashes (`-`) at the beginnig of its name.

For the record, UIDs for rules from the `/etc/openhab/rules` contain the filename, followed by a dash and digit (number of the rule within the `.rules` file).  This UID generation logic is much better.

**Comment by florian-h05** [comment]
Hello @dilyanpalauzov,

after some investigation and looking at 
https://github.com/openhab/openhab-js/blob/5bf74e19a5cbdd7f2fc3f10b5ea29d91571a47f7/rules/rules.js#L235

I think the problem is your rule name in kyrillic (is that correct??) letters, because those are no word characters (A-Z, a-z, 0-9). 
I think that openHAB could not handle those characters and therefore they are replaced for the rule id.

> For the record, UIDs for rules from the /etc/openhab/rules contain the filename, followed by a dash and digit (number of the rule within the .rules file). This UID generation logic is much better.

I know, I am not sure if that is possible as well in JS Rule. 
Personally, I prefer the current generated uid which consists of the rule name and some uid letters.

Please keep in mind that you can manually set the rule uid with the `id` param in the rule configuration object.

**Comment by dilyanpalauzov** [comment]
Since many `-` dashes in a row contain no information, it would be better, if the generated rules do not contain sequences of dashes, as result of transliteration.

In the above example, the UID `----------------------------------325106c4-0fc3-49f9-a466-a988921c6bff` shall be just `325106c4-0fc3-49f9-a466-a988921c6bff`.

**Comment by florian-h05** [comment]
I have a different opionion on that — for the most users, the current way is better, because of the rule name is contained in the uid. For the rare cases where the user (you) is using a rule name that cannot be used in the uid, you should stuck with the auto-generated uid and manually set it:

```javascript
rules.JSRule({
    name: 'Помпи промяна горна/долна граница',
    description: 'Помпи промяна горна/долна граница',
    triggers: [
        triggers.ItemStateChangeTrigger('pompi_on', null, null, "W1"),
        triggers.ItemStateChangeTrigger('pompi_off', null, null, "W2")
    ],
    execute: (data) => {
        execute()
    },
    id: 'myruleuid'
})
```

**Comment by dilyanpalauzov** [comment]
For the most users the current logic is good, and I do not ask to change the current logic for the most users.

For the rare cases, when the generated UID has many dashes in a row, I propos stripping the dashes.

**Comment by florian-h05** [comment]
Okay, I understand what you mean.
I will take a look at this probably when I have some spare time.

**Comment by jpg0** [comment]
FYI this is solved pretty easily by updating the regex to greedily consume all the non-matching characters by appending a plus `/[^\w]+/g`.

**Comment by florian-h05** [comment]
@jpg0 
Okay thanks, do you want to contribute?
