### ISSUE TITLE
js api missing xxBetween persistence methods

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-js#156]
Openhab-js api is missing xxBetween methods, e.g. <Item>.averageBetween

See https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/extensions/persistenceextensions

## Your Environment

* Version used: (e.g., openHAB and **JS Scripting add-on version**)
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):

**Comment by florian-h05** [comment]
Thanks for the hint, I‘ll add them.
