### ISSUE TITLE
[cache] Change implementation to the new access-tracking cache in core

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#184]
With the addition of both a `privateCache` (per script identifier, useful for sharing timers) and a `sharedCache` (shared across all scripts from all languages) in https://github.com/openhab/openhab-core/pull/2887, we have to update our implementation of `cache`.

Backward compatibility must be kept!!

After we have a solution here, we can remove the [SharedCache](https://github.com/openhab/openhab-addons/blob/e979be49114a0e9f234f19ce57b9e11cc2b4493a/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/scope/SharedCache.java) from JS Scripting.

My proposal is:
- for the current methods of `cache`:
  - check if the new caches from core are available
  - if they are available, log a deprecation warning and use the shared cache from core instead of the addon‘s shared cache implementation so that we can remove SharedCache from the addon
  - if they are not available (means the library runs on an „old“ openHAB version), do nothing and keep the current behaviour
- add a `private` property to `cache` to allow access to the private cache
- add a `shared` property to `cache` to allow access to the shared cache

@rkoshak @digitaldan @jpg0 WDYT?

**Comment by florian-h05** [comment]
@wborn FYI: Before removing the SharedCache from the JS Scripting add-on, we/I  have to change the implementation of the cache in the helper library.

**Comment by rkoshak** [comment]
Sounds good to me.

**Comment by rkoshak** [comment]
Sounds good to me.
