### ISSUE TITLE
[metadata] Add support for configuration

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#189]
This has come up a number of times on the forum. There is some demand to support getting and modifying not just metadata values but also the configuration dict. This would add a few methods to the metadata namespace to support retrieving, adding, deleting and upserting metadata that also includes the configuration.

EDIT by @florian-h05:
See https://community.openhab.org/t/set-statedescription-for-proxy-item-from-a-rule-js-scripting/141690/5.

**Comment by rkoshak** [comment]
Looking more closely at metadata.js, you are right, upsertValue, addValue, and updateValue do have a config argument that takes a Map. However, the function names are very misleading. A bigger concern though is it's missing a getter that returns the config. Also, updateValue basically throws away the `config` since `createMetadata` doesn't use the `config`. argument passed to it.

So it's a bit of both. It is missing from the docs but there is at least one bug and a missing capabilities.

**Comment by florian-h05** [comment]
You are right, the implementation is a little bit „weird“. I’ll have a look at this, but I don’t think that it will make it into the 3.4.0 release because the feature freeze is coming on Sunday.
But maybe we can declare this as bug fix??

**Comment by jpg0** [comment]
FYI when I wrote this part of the library, I had almost no idea how openHAB configuration actually worked. I did it only to support some specific use-cases I had, so I'm not surprised that it's weird (and tbh I was confused about the distinction between metadata and configuration). I wouldn't be surprised if the best course of action would be to completely replace it!

**Comment by florian-h05** [comment]
A small update how it’s going: I already figured out how to reimplement metadata, I just need to clean up the code and create a PR.
