### ISSUE TITLE
`toString()` doesn‘t properly represent Items, Things

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#197]
Calling the `toString()` method on native Java openHAB Items returns a string that represents the Item with it‘s metadata etc. (e.g. `F2_Office_Main_Light (Type=SwitchItem, State=OFF, Label=Deckenlampe AZ, Category=light, Tags=[Lightbulb], Groups=[LichterAZ])`), but calling `toString()` on the JS version tries to stringify the object: 

```
{
  "rawItem": {},

  "history": {

    "rawItem": {}

  },

  "semantics": {

    "rawItem": {}

  }

} 
```

[`ThingImpl`](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.thing/src/main/java/org/openhab/core/thing/internal/ThingImpl.java) doesn‘t provide a `toString` method, maybe one should be introduced?

FYI have a look at the `toString` method of [`GenericItem`](https://github.com/openhab/openhab-core/blob/97299c7dcb3c0527071629903cf1b839aad08a37/bundles/org.openhab.core/src/main/java/org/openhab/core/items/GenericItem.java#L273).

This issue is just a reminder for myself and to track this.

@stefan-hoehn Das hier ist das Problem wieso das Loggen eines Items von Blockly aus auf JS Scripting nicht mehr so funktioniert wie auf Nashorn.

**Comment by stefan-hoehn** [comment]
Thx, @florian-h05 , I appreciate if that would be done. Do you need support here?

**Comment by florian-h05** [comment]
Thanks for asking, I’d need a review for my PR https://github.com/openhab/openhab-js/pull/198.

**Comment by florian-h05** [comment]
Closing as #198 has been merged and I don't see the need in providing a Thing serialization from core.
