### ISSUE TITLE
Some typings are wrong

### ISSUE THREAD

**Issue by Owlbertz** [openhab/openhab-js#208]
After switching to the manual import I noticed that several typings are wrong:

```js
triggers.ItemStateChangeTrigger('Test_Alarm', null, 'ON')
```
According to the IDE the second parameter must either be `string` or `undefined` - but both the docs and the example within the IDE show `null` being used.

```js
triggers.SystemStartlevelTrigger('100')
```
According to the IDE the `100` needs to be a string, but both the docs and the example within the IDE show a number being used.

**Comment by florian-h05** [comment]
In the first case, the docs are wrong. The parameter is optional, to skip it `undefined` should be used.
In the second case, the type definitions and the docs are correct, but it may be possible that they are not released yet or you don't have downloaded them.
