### ISSUE TITLE
[items] Extend `metadata` & `itemchannellink` APIs

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-js#220]
See https://github.com/openhab/openhab-js/pull/212

I've been working with creating, updating , and deleting items with procedural scripts, and it would be much more powerful if sometimes I didn't have to specify item names or the precise metadata values etc. 
Sometimes I would like to delete all channel links from all items, or a selection of items, or a single item. 
Sometimes I would like to delete all invalid channel links.

**Comment by florian-h05** [comment]
What can be added is:

For metadata:
- remove all metadata from an Item
- get all metadata namespaces an Item has

For ItemChannelLinks:
- remove all links for an Item
- remove invalid/orphaned channel links

Doing such operations on all Items is possible by doing:

```javascript
items.getItems().forEach((item) => item.someOperation);
```
