### ISSUE TITLE
[docs] Add a note about let & const not working in UI scripts

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#235]
Although all our code examples try to avoid using `let` or `const` and instead use `var`, we should add a note to the docs to clearly state that `let` and `const` are not working in UI rules due to some limitations in openHAB. 

@rkoshak WDYT?

**Comment by rkoshak** [comment]
I think it's a good idea. However, maybe we should also present how a user can wrap their script in an anonymous function which would allow them to use `let` and `const`. 

Either way, we need to make sure to include the fact that it's only at the top level of the script where they cannot be used. Inside functions it's fine.
