### ISSUE TITLE
Add support for Quantity to toZDT()

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#245]
The current code handles QuantityType but now that we support our own JS implementation we should also support that too.

I'm mostly adding this as a reminder to myself but if someone gets to it before me so much the better. ;-)

**Comment by florian-h05** [comment]
toZDT should handle Quantity as well:

https://github.com/openhab/openhab-js/blob/82a465bdf08895b3b2664ceb9d4bf8363795bf09/time.js#L255-L258

I’ve already added this some time ago.

**Comment by rkoshak** [comment]
I completely missed that. As I was reading through it I read that as QuantityType. My bad.
