### ISSUE TITLE
itemhistory.js only works with the default persistence

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#26]
There is no way to pass the name of the persistence service we want to query. By default, OH 3 ships with rrd4j installed and configured as the default persistence. However, because it saves a value every minute, the calls to `previousState` and `latestState` are almost certainly not going to be what you want. 

Furthermore, they don't actually return the HistoricState Object which contains both the state and the date time of that state. Often users will want to know not only that historic state but when that state occurred.

Finally, because this is in a separate file an imported the autogenerated docs appears to miss documenting the functions. The only reason I was able to discover these functions exist was by searching the repo to see if PersistenceExtension was imported.

I'm sensitive to the amount of work and complexity involved if we were to implement every variation of every PersistenceExtension method so I propose that we we Java.type it in actions.js so it's available as an action (which is kind of what it really is) and leave the relatively simple three functions implemented in itemhistory.js as is. 

Thoughts?

**Comment by jpg0** [comment]
I would certainly support exposing the raw Java objects, although I'd suggest a small test first - some of these areas I originally implemented just enough to get my rules running, and sometimes I did it because I have problems using the raw Java directly, so let's just make sure that it works well from JS. Typically the problems that arose when using Java objects directly were translation issues between the languages, I remember handling of collection classes being a pain point, and also occasionally lookup of the correct Java function based on JS parameters.

**Comment by digitaldan** [comment]
Just looking at this now, there are a lot of methods as well we are not exposing from:

https://www.openhab.org/javadoc/latest/org/openhab/core/persistence/extensions/persistenceextensions

Curious if we want to maybe expose these on items in a slightly different way, 

```javascript
const item = items.getItem("Lights");
//default persistance
item.history.historicState​();

//influxdb  persistance
item.history.historicState​("influxdb");
```

And also expose all the methods listed in the persistenceextensions?

**Comment by jpg0** [comment]
Do we need both `history` and `historicState` chained? Can't we have a single call (`item.history` vs. `history(...)` or `history[...]`)?

**Comment by digitaldan** [comment]
I just opened #27 , this adds all the persistence methods directly on the OHitem  and exposes an optional persistance id, let me know what you think.  I include a screen shot in that PR of a snippet of what the outputed docs looks like

**Comment by digitaldan** [comment]
this has been merged
