### ISSUE TITLE
Adjust behaviour of getThing('someThing').setLabel('newLabel') so that the change persists after a restart of OpenHAB

### ISSUE THREAD

**Issue by proggprod** [openhab/openhab-js#269]
## Your Environment

 OpenHAB 4.0.0M3
JS Scripting

Please change the behaviour of getThing('someThing').setLabel('newLabel') so that the change persists after a restart of OpenHAB.
I haven't tested it, but .setLocation(location) and .setProperty(name, value) should also be persistent if they aren't already.

Reference https://github.com/openhab/openhab-core/issues/3648.

**Comment by florian-h05** [comment]
#270 has more detail, therefore closing this.
