### ISSUE TITLE
Rule Builder API doesn’t support the DateTimeTrigger

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-js#280]
Currently there is no [Rule Builder trigger](https://www.openhab.org/addons/automation/jsscripting/#rule-builder-triggers) for `DateTimeTrigger` (see https://www.openhab.org/addons/automation/jsscripting/#jsrule)

As an example, this cannot be built with the rule builder:

```javascript
rules.JSRule({
    name: "Dishwasher start",
    description: "Start dishwasher based on calculated price",
    triggers: [triggers.DateTimeTrigger('Dishwasher_CalculatedStartTime')],
    execute: event => {
        if (items.Dishwasher_RawState.isUninitialized || items.Dishwasher_RawState.numericState != 4 || items.Dishwasher_CalculatedStartTime.isUninitialized) {
            return;
        }
        items.Dishwasher_Switch.sendCommand("ON");
    }
});
```

This would be a nice addition.

## Your Environment
* Version used: 4.0 with bundled openhab-js

**Comment by jlaur** [comment]
To be precise: I'm not sure if actually supported, but it's not documented. I just noticed that there is a RuleBuilder example with `timeOfDay("SUNSET")`, but actually this is not documented besides the example.

The `TimeOfDayTrigger` is documented just before the `DateTimeTrigger` in the [JSRule](https://www.openhab.org/addons/automation/jsscripting/#jsrule) section.

**Comment by florian-h05** [comment]
> I just noticed that there is a RuleBuilder example with timeOfDay("SUNSET"), but actually this is not documented besides the example.

There is no actual support for that, the source code does not contain that. I will add the timeOfDay trigger, however it does not support something like `SUNSET` (looking at openHAB Core).

**Comment by jlaur** [comment]
> I will add the timeOfDay trigger, however it does not support something like `SUNSET` (looking at openHAB Core).

In that case the [example](https://next.openhab.org/addons/automation/jsscripting/#rule-builder-examples) should probably be updated:

```javascript
// Turn on the kitchen light at SUNSET
rules.when().timeOfDay("SUNSET").then().sendOn().toItem("KitchenLight").build("Sunset Rule","turn on the kitchen light at SUNSET");
```

**Comment by florian-h05** [comment]
I have created a PR to add the trigger, see #291 and I also updated the documentation.
The sunset rule is now triggered by using the Astro binding.

You can test the PR by installing my fork, execute in `$OPENHAB_CONF/automation/js`:

```
npm install git+https://github.com/florian-h05/openhab-js.git#rule-builder
```
