### ISSUE TITLE
Polyfills to replicate node.js globals

### ISSUE THREAD

**Issue by simonihmig** [openhab/openhab-js#3]
I was trying to make the popular [xstate](https://xstate.js.org/) library work in an (file-based) automation rule (for which it is super useful btw!). But it failed in multiple, hard to debug ways, as the GraalVM environment is not quite the same environment as node (or the browser):
* it expects to have a `global` object where alls globally defined variables live (which was introduced by node.js). While GraalVM correctly supports the newer and actual ES standard for this ([`globalThis`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis)), it does not have a `global`, which this and probably many other libs still seem to expect. (xstate's [implementation](https://github.com/statelyai/xstate/blob/9b456beb316e5de6a73fb295142f2f935b7f8c65/packages/core/src/devTools.ts#L18-L30) is actually bad, as it looks for those legacy objects and does not even take `globalThis` into account - I'll submit a PR for it)
* related to the older discussion in https://github.com/jpg0/ohj/issues/14, there is no global `setTimeout()` function, which - albeit no ECMAScript standard AFAIK - any library will practically expect to exist, as 99,99% of the real-world JS environments (node + browser) have it
* it did a check for `process.env.NODE_ENV === 'production'`, which is quite common

I was able to basically provide polyfills for these missing platform features in my script, which does fix the issue and makes at least this library (and probably many others that rely on the same features) work. Putting those in my actual automation scripts everywhere where those issues arise is certainly not the best way. We could either
* integrate those into openhab-js (I can provide a PR)
* or does it make sense add those into the actual openhab addon, so they are available in every script? (see https://www.graalvm.org/reference-manual/js/Modules/#global-symbols-pre-initialization)

To be clear, I am *not* talking about polyfilling the node.js importable modules like `fs` and others, that is certainly out of scope!

**Comment by digitaldan** [comment]
Funny, i already started doing this as well :-)  After realizing after several days of trying that there was no way of redirecting console log output in GraalJS (short of redirecting stderr and stdout for the whole JVM, and i tried everything), i conceded  i needed to poly fill this, actually one of the GrallJS developers recommended this on their forum.  My thoughts here is the first thing most people do when trying out JS is to `console.log("hello world")` and if we didn't support that out of the box, it would look rather crappy. 

https://github.com/digitaldan/ohj/blob/ohj-improvements/console.js

**Comment by simonihmig** [comment]
@jpg0 any thoughts on where polyfills like those should go, into this lib or the addon itself?

> https://github.com/digitaldan/ohj/blob/ohj-improvements/console.js

@digitaldan This is cool! Much more feature complete than my first "make it work" attempt. But I wonder how you use it, as it seems you are exporting an alternative console object that you would have to import to use it. Which is fine for your own code. But what about 3rd party npm packages using `console`? This was what I was mostly interested in, as I was missing all kinds of logs and warnings from those. So I basically monkey patched `console` so that any code would use the new version. Some like this:

```js
console.log = (...args) => {
  logger.info(...args);
};
```

**Comment by digitaldan** [comment]
>But what about 3rd party npm packages using console?

I was thinking from a simple scripting perspective, but you are right, there's going to be odd output in the karaf console/cli right now if  npm packages try to use any of the console logging (this is where stdout goes).   Should the JSScripting binding provide certain builtins like console.log and  setTimeout?  I would vote yes, my guess is there is a certain level of functionality we should provide that everyone is probably going to appreciate.

We probably are not going to polyfill everything (as you mention), so first if we agree that certain globals/builtins should be provided, then I think these are 3 examples (global, settimeout, console) of ones we would want to support, the Global symbols pre-initialization function looks promising for this.  In any case, I think this is a good place to discuss, even if it ends up living in the JSScripting binding.

**Comment by jpg0** [comment]
Yes, I'm a big supporter of adding polyfills with the intention to make the openHAB environment as close as possible to standard JS... which is pretty much either what is supported in browsers or NodeJS. So anything which increases compatibility with these I believe should just be there. So I also vote for making them available in the runtime, rather than needing to be imported.

**Comment by jpg0** [comment]
No I don't: go for it

**Comment by simonihmig** [comment]
I would have been able to provide a PR to this library, but contributing to Java code (as we agreed to add the polyfills to the addon) is beyond my pay grade! :wink:

Here is what I currently have as my `polyfills.js`, in case that helps:

```js
const ScriptExecution = Java.type(
  'org.openhab.core.model.script.actions.ScriptExecution'
);
const ZonedDateTime = Java.type('java.time.ZonedDateTime');

const logger = require('./log');

function setTimeout(cb, delay) {
  return ScriptExecution.createTimer(
    ZonedDateTime.now().plusNanos(delay * 1000000),
    cb
  );
}

function clearTimeout(timer) {
  if (timer.isActive() && !timer.isRunning()) {
    timer.cancel();
  }
}

globalThis.setTimeout = setTimeout;
globalThis.clearTimeout = clearTimeout;
globalThis.global = globalThis;
globalThis.process = { env: { NODE_ENV: '' } };

console.log = (...args) => {
  logger.info(...args);
};

module.exports = {};
```

The `console` polyfill is obviously largely incomplete. But `setTimeout`, `clearTimeout` and the global objects proved to be helpful. `setInterval` is missing, but can hopefully be also replicated in a similar manner.

**Comment by digitaldan** [comment]
Thanks @simonihmig , thats a great place to start.  

I just tried out the `js.commonjs-global-properties` option and it does indeed do we we want.

@jpg0 there is one issue i'm facing, i'm assuming the globals properties is being loaded in the global context, so if we want to be able to include any of the @runtime OH builtins we need your require injection logic.  Problem is i can't seem to inject it at a global level here
https://github.com/openhab/openhab-addons/blob/163a34fca4988e3ea6a3ce6d0666092478411f6a/bundles/org.openhab.automation.jsscripting/src/main/java/org/openhab/automation/jsscripting/internal/OpenhabGraalJSScriptEngine.java#L132

I naively assumed i could add
`delegate.getBindings(ScriptContext.GLOBAL_SCOPE).put(REQUIRE_WRAPPER_NAME, wrapRequireFn);`
But this is returning a null binding, and so the loaded globals file errors out on the `__wraprequire__` placeholder that gets injected.  I'm temporarily not injecting this for now, but it would be nice to support.

**Comment by digitaldan** [comment]
Honestly i'm not sure how much we get using the built in global property loader vs just calling `eval()` of our global file before we call `eval()` of the user script.  

It seems like GraalVM is calling `eval()`  on the "js.commonjs-global-properties"  file for every script execution , so if we don't need to use this,  my question to @jpg above would not apply.  Since we are setting values on the GloablThis, I'm not sure it matters what "scope" this runs in ?  

This is starting to get in the gray areas of the GraalVM engine that i don't really understand yet.

**Comment by digitaldan** [comment]
Here's a link to what i have been using.  This also is loaded as a normal node module, so if you have `@global.js` in your personal folder, it will pick that up first before defaulting to the one from the binding.  This makes development pretty nice, and allows power users to override any of it . 

https://github.com/digitaldan/openhab-addons/blob/91e10330b25397a84e6c1c8c44fdfe602b746933/bundles/org.openhab.automation.jsscripting/src/main/resources/node_modules/@globals.js

**Comment by jpg0** [comment]
I have no problem with just eval'ing the setup stuff before the script is run. Just ensure that it works across modules - for example the 'wraprequire' stuff needs injecting for each module.

**Comment by digitaldan** [comment]
Sounds good @jpg0 , thanks for the feedback.  I'm still getting comfortable with GraalVM, and do not have your level of understanding of it, so very much appreciate your thoughts on the matter.  I'll probably open up a PR soon for the binding and at least have a place to start a discussion around it.  While it's working for me now, it may not be the most optimal solution.  

FYI, if i seem rather active on this project, i have mostly the entire next week off for our Thanksgiving holiday here in the states and so have time to contribute.

**Comment by jpg0** [comment]
Also it's great that you are very active on the project - I am quite happy for you to take the lead as I have little time to spend on it, but am just happy that I've been able to donate the existing code and it will be used!

**Comment by digitaldan** [comment]
closing as we have a pretty robust polyfil now in the proposed binding.
