### ISSUE TITLE
Expose ZonedDateTime

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-js#32]
I feel like `ZonedDateTime` , and to a lessor extent `Duration` will be needed in rules.  Native JS Dates just don't have the functionality built in. 

I'm curious what others thoughts are about where this would live?  On the `utils` namespace?  On its own ?

**Comment by jpg0** [comment]
I have not had the need to use ZonedDateTime (my house is only in a single TZ! :-P), but instead of Duration I used some native JS libraries. Even if you do add some ability to interop with these classes, you are still likely to need to work with JS dates too if you want to support existing JS libs.

**Comment by digitaldan** [comment]
>you are still likely to need to work with JS dates too if you want to support existing JS libs.

Yeah, and you can use a JS Date where ever a ZoneDateTime object is needed (GrallVM converts it), but doing simple things like adding time (now + 24 hours) is a pain without 3rd party libraries.  So trying to figure out the best out of the box experience for dealing with this.

**Comment by Confectrician** [comment]
Isn't ZonedDateTime already the prefferd solution according to the examples/tutorials/questions one can find in the community forum?

Maybe then it would be awesome to have something available that users already are familiar with.

**Comment by jpg0** [comment]
> Isn't ZonedDateTime already the prefferd solution according to the examples/tutorials/questions one can find in the community forum?
> 
> Maybe then it would be awesome to have something available that users already are familiar with.

Whilst this is _currently_ true, isn't it because historically users were _forced_ to do this? I would expect that JS script writers would be more familiar with a pure JS solution rather than a Java-based one? Saying this, I do agree that we need some sort of ZonedDateTime support, but primarily for migration and interop, rather than actually handling date manipulations and calculations in new JS scripts.

**Comment by digitaldan** [comment]
So the question is where does something like this live?  In utils?  exported directly like `items` or `actions` ? 

Ideally something like [luxon](https://github.com/moment/luxon/) would be available as an alternative to ZoneDateTime and the native Date, but i'm not sure of the ramifications of including that ( size, complexity, interoperability, etc....)

**Comment by jpg0** [comment]
Personally I am not a fan of trying to include things like this. What if the library becomes deprecated (like moment.js), or other, better alternatives become more popular? My view is that we should ensure we handle interop with JS Dates (and probably epoch-seconds), then let script writers choose their date library.

I do understand that this makes things a bit harder for UI rules however. Maybe there should be something in the UI which allows one-click installation of npm libraries, and we can even suggest some.

My fear is that if we start bringing in various JS libraries as default then we couple our success to theirs (plus lose flexibility).

**Comment by Confectrician** [comment]
> My fear is that if we start bringing in various JS libraries as default then we couple our success to theirs (plus lose flexibility).

100% Agreed

> then let script writers choose their date library

This may be suitable for (more) advanced users, but i doubt that we will cover beginners with this.
(At least if js scripting aims to be a solution for openHAB users with all different expirience levels.)

**Comment by digitaldan** [comment]
>My fear is that if we start bringing in various JS libraries as default then we couple our success to theirs (plus lose flexibility).

yep, thats the ramifications i am thinking about.  I also think it probably crosses a line of what is "core" and what is optional.  

One thought is we could have a `time` object which basically exposes the `java.time` package which contains the following
```
Clock
Duration
Instant
LocalDate
LocalDateTime
LocalTime
MonthDay
OffsetDateTime
OffsetTime
Period
Year
YearMonth
ZonedDateTime
ZoneId
ZoneOffset
Enums
DayOfWeek
Month
```

We could provide a sane subset of these

**Comment by jpg0** [comment]
I think that is fine - just something which provides easier access to Java constructs. I think that we should avoid accepting these types in the JS API however, and use JS dates instead. Ideally we would also provide some convenience functions to convert between the two.

**Comment by digitaldan** [comment]
My thinking is most of these are for interacting with ZoneDateTime, which actions and other OH native stuff needs.  I would rather prefer to use native JS Dates , which are interchangeable with ZoneDateTime, but it's truly a pain to do any time manipulation with (like create a date 2 days in the future or past) .

**Comment by digitaldan** [comment]
so for example, our time.js class could be as simple as

```javascript
module.exports = {
    Clock: Java.type("java.time.Clock"),
    Duration: Java.type("java.time.Duration"),
    Instant: Java.type("java.time.Instant"),
    LocalDate: Java.type("java.time.LocalDate"),
    LocalDateTime: Java.type("java.time.LocalDateTime"),
    LocalTime: Java.type("java.time.LocalTime"),
    MonthDay: Java.type("java.time.MonthDay"),
    OffsetDateTime: Java.type("java.time.OffsetDateTime"),
    OffsetTime: Java.type("java.time.OffsetTime"),
    Period: Java.type("java.time.Period"),
    Year: Java.type("java.time.Year"),
    YearMonth: Java.type("java.time.YearMonth"),
    ZonedDateTime: Java.type("java.time.ZonedDateTime"),
    ZoneId: Java.type("java.time.ZoneId"),
    ZoneOffset: Java.type("java.time.ZoneOffset"),
    DayOfWeek: Java.type("java.time.DayOfWeek"),
    Month: Java.type("java.time.Month"),
}
```

**Comment by jpg0** [comment]
Not sure if this helps, but in my scripts I heavily used [JS-Joda](https://js-joda.github.io/js-joda/). It's a JS port of [Joda Time](https://www.joda.org/joda-time/), which was what effectively became the `java.time` package.

**Comment by digitaldan** [comment]
I am aware of Joda Time, but not aware of JS-Joda, will definitely take a look!

**Comment by digitaldan** [comment]
So JS-Joda looks  very nice, and would be a great drop in replacement for java.time.  If we were to consider using this despite some of the concerns above, we could probably implement our own TypeMapper in GraalVM to auto convert to and from a Java ZonedDateTime to JS-Joda ZonedDateTime.  Thoughts?  It would then be a drop in replacement. 

https://www.graalvm.org/sdk/javadoc/org/graalvm/polyglot/HostAccess.Builder.html#targetTypeMapping-java.lang.Class-java.lang.Class-java.util.function.Predicate-java.util.function.Function-

I would not want to make a habit of doing this, but....... time manipulation is core to so many rules, this keeps coming up as I write the documentation, so i think this is a special case the deserves a little more consideration.

**Comment by digitaldan** [comment]
FYI I was able to get JS-Joda working as a drop in replacement for native ZonedDateTime with the conversion happening in the actual engine.  Here's the GraalVM conversion logic:

```java
 HostAccess hostAccess = HostAccess.newBuilder(HostAccess.ALL)
                .targetTypeMapping(Value.class, ZonedDateTime.class, (v) -> v.hasMember("withFixedOffsetZone"), v -> {
                    return ZonedDateTime
                            .parse(v.invokeMember("withFixedOffsetZone").invokeMember("toString").asString());
                }, HostAccess.TargetMappingPrecedence.LOW).build();
```

I'm really impressed with how strict JS-Joda is with compatibility with what is now java.time , and that it has Zero dependencies, which is very unusal in the NPM world.  

I know we agreed that adding libraries can cause bloat and possible  future issues, but again i think time is a special case, and having to deal with Java objects in Javascript to do this doesn't feel right.  Plus the documentation is pretty good for JS-Joda, easier then having to read java-docs, but the API is so similar (identical ?) , existing openHAB how-to guides on time will continue to be valid

**Comment by Confectrician** [comment]
This sounds very good to me. :)

**Comment by digitaldan** [comment]
see #38

**Comment by digitaldan** [comment]
I just merged to get this into the milestone release, please feel free to open another issue if there are concerns or changes needed, nothing is set in stone and I'm happy to accommodate others opinions.
