### ISSUE TITLE
addActionButton Issue

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-js#354]
when using the  `addActionButton`  when building notifications, the action command seems to be altered, for example,

`command:Sonos_Patio_Control:PAUSE` --> `command:Sonos_Patio_Control:PAUSE=undefined`

This does not happen when using `actions.NotificationAction.sendNotifcation`  to send actions.  

I have not dug in yet to see what the issue is.

**Comment by florian-h05** [comment]
Can you add some debugging around https://github.com/openhab/openhab-js/blob/ea987453ac0e08b0e59c1d2ebe384b9dff5831cb/src/actions/notification-builder.js#L186?

Probably also try it with chaining the strings using + instead of string templates.

**Comment by florian-h05** [comment]
The weird thing is, why is the unit test succeeding? For the unit case, the action is not altered …

**Comment by digitaldan** [comment]
Sorry, this is my error, i should have taken more time before opening this issue 🤦    I was adding a single String as `Pause=command:Sonos_Patio_Control:PAUSE` , not realizing `addActionButton` takes two args, title and action as separate args.

**Comment by florian-h05** [comment]
Glad there is no real issue!
