### ISSUE TITLE
Make parameter in actions.notificationBuilder() optional

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-js#368]
Most of my notifications only contain a title as IMO it looks better on Android to have a title than a message. Thus most times I pass an empty string to `actions.notificationBuilder("")`. Maybe this parameter could be made optional with `""` as default value.

**Comment by mueller-ma** [comment]
I discovered that the parameter is actually optional. When using it without a parameter, it crashes the Android app, but that's a different issue (https://github.com/openhab/openhab-android/pull/3794).

**Comment by florian-h05** [comment]
It was actually not planned that this is supported, rather works by coincidence.
I have just checked the add-on code, null for message is not supported by still works in the cloud connector code.

But I think it would be better to pass an empty string, WDYT?
And it has to be marked as optional in the JSDoc.

**Comment by florian-h05** [comment]
See #370.
