### ISSUE TITLE
Function to send Item updates only in some cases

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-js#369]
I have a rule "when it gets dark outside, turn on the lights to 20%": `items.getItem("Lights").sendCommand("20")`. However this will darken the light when it has been turned to 100% manually before. I wrapped it in a `if` to avoid this, but maybe a function for this could be added, similar to `sendCommandIfDifferent()`:
- `increaseValueTo(value)`: Send the command only when `value` is larger than the current state.
- `decreaseValueTo(value)`: Send the command only when `value` is smaller than the current state.

This only applies to `Number` Items.

Feel free to close this if you think it's too niche.

**Comment by florian-h05** [comment]
It's type of niche, but I see the use case.

> This only applies to Number Items.

I would say `Dimmer` Items, not `Number`. Did you mean that?

**Comment by mueller-ma** [comment]
Hm, it applies to all Items that can have a state as a number, e.g. also Rollershutter.
