### ISSUE TITLE
Adjust use of deprecated `DateTimeType::getZonedDateTime`  method in `time::toZDT`

### ISSUE THREAD

**Issue by florian-h05** [openhab/openhab-js#404]
Due to https://github.com/openhab/openhab-core/pull/3583,
it is required to adjust 

https://github.com/openhab/openhab-js/blob/5ebf646404b75de3c26b2d810f25520e3843ca12/src/time.js#L189

and 

https://github.com/openhab/openhab-js/blob/5ebf646404b75de3c26b2d810f25520e3843ca12/src/time.js#L294

to `DateTimeType.getZonedDateTime(zoneId)`.

This however cannot be done without breaking backwards compatibility with openHAB < 4.3, so we have to postpone this change to the next breaking openhab-js release.

**Comment by jlaur** [comment]
@florian-h05 - actually there is one thing we can do without breaking anything. `getZonedDateTime(ZoneId)` is just a convenience method:

https://github.com/openhab/openhab-core/blob/241e55f15756a0346069f23ff4b5da57a893cced/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java#L156-L164

so we could do something like (probably I'm mixing Java and JavaScript, but you get the idea):
```java
    return javaZDTToJsZDT(rawState.getInstant().atZone(time.ZoneId.systemDefault()));
```

WDYT?

**Comment by florian-h05** [comment]
If getInstant is available long enough, this is a good solution 👍

Just noting that we need to use the time zone from the timeZoneProvider because we are dealing with Java ZDT here.
Fortunately timeZoneProvider is already available in time.js, so if you want you can create a PR.

**Comment by jlaur** [comment]
> If getInstant is available long enough, this is a good solution 👍

It was introduced in openhab/openhab-core#3287 and is there to stay. 🙂

> Just noting that we need to use the time zone from the timeZoneProvider because we are dealing with Java ZDT here.
Fortunately timeZoneProvider is already available in time.js, so if you want you can create a PR.

Sure, I will give it a go. 👍

Side comment: I plan to also have a look if we can provide more `Instant` functionality like we have `time.toZDT`. I seem to find more and more cases in rules where working with `ZonedDateTime` is not needed. I will probably create a new issue with some concrete suggestions, so we can discuss it before writing any code.
