### ISSUE TITLE
Issue with joda-js ZonedDateTime parser - default format not compatible with DateTimeItem state value

### ISSUE THREAD

**Issue by marcinczeczko** [openhab/openhab-js#45]
I was working on the rule that uses openhab `DateTimeItem` state to get the time to schedule some timers. 
However, I found strange issue that parsing the state string as it is throws joda parsing exception. I had to instantiate my own formatter to get it working. Please take a look below, but in general now idea if the problem lies in the openhab datetime format, joda-js default format or maybe oh-js itself.

### how to reproduce
- In the rule, or script just do this
```js
let tm = "2021-12-22T19:08:05.123+0100";
console.log(time.ZonedDateTime.parse(tm));
```
An exception is being throws as follows
```
19:14:29.215 [ERROR] [.internal.handler.ScriptActionHandler] - Script execution of rule with UID 'sun_state_rule' failed: org.graalvm.polyglot.PolyglotException: JsJodaException: Text '2021-12-22T19:08:05+0100' could not be parsed at index 19: 2021-12-22T19:08:05+0100, at index: 19
```
### workaround
- As a workaround I simply implemented the parsing method to have it parsed.
```
function toJoda(itemDateTime) {
      const df = time.DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
      return time.ZonedDateTime.parse(itemDateTime, df);
}
```
### findings
Didn't get much time looking at the defaults in joda-js, but looks like it expects timezone in the form of `+01:00` with colon symbol, while openhab reports with it, e.g. `+0100`. So, these is parsed correctly
```js
let tm = "2021-12-22T19:08:05.123+01:00";
console.log(time.ZonedDateTime.parse(tm));
```

**Comment by marcinczeczko** [comment]
Looks like openhab formats Datetimeitem state using RFC timezone https://github.com/openhab/openhab-core/blob/68ff739a506db0cf0ea464c5853b5e83dc0d3962/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/DateTimeType.java#L181, while joda-js uses ISO version of timezone.

**Comment by jpg0** [comment]
This is how I have been using js-joda:

```
const ISO8601Formatter = JSJoda.DateTimeFormatter.ofPattern("uuuu-MM-dd'T'HH:mm:ss.SSS[xxxx][xxxxx]");

const getTimeFromItem = function (itemName, now_dt) {
  let item_dt_str = items.getItem(itemName).state;
  let item_zdt = JSJoda.ZonedDateTime.parse(item_dt_str, ISO8601Formatter);
  return item_zdt.toLocalTime();
};
```

So I think that this formatter needs to be included in the openHAB-to-js-joda code, or set as the default (if possible).

**Comment by digitaldan** [comment]
Hmm, let me take a look

**Comment by digitaldan** [comment]
So I'm thinking we could monkey patch this pretty easily like so 

```javascript
const time = require('@js-joda/core');
const rfcFormatter = time.DateTimeFormatter.ofPattern("uuuu-MM-dd'T'HH:mm:ss.SSS[xxxx][xxxxx]");
const targetParse = time.ZonedDateTime.parse;
time.ZonedDateTime.parse = function (text, formatter = rfcFormatter) {
    return targetParse(text, formatter);
}
module.exports = time;
```

Thoughts on a better way ?

**Comment by digitaldan** [comment]
See #51
