### ISSUE TITLE
Events are not available in the rule body ?

### ISSUE THREAD

**Issue by marcinczeczko** [openhab/openhab-js#48]
I tested simple rule using ECMA 2021 in OH that is triggered by Item state change. If I log the event triggering as follows
```
console.log("TEST: ", event);
```
Then I'm getting the text in log
```
2021-12-27 18:37:14.108 [INFO ] [org.openhab.automation.script       ] - TEST: Item 'SUN_STATE' changed from DARK to BRIGHT
```
Ok, but I was struggling to get any more information other that the text in log. How to get the state to which the item was changed ?
I tried to discover builing a json string from the object props, but apparently it is empty
```
console.log("JSON: ", JSON.stringify(event));
```
The log is 
```
2021-12-27 18:37:14.111 [INFO ] [org.openhab.automation.script       ] - JSON:  {}
```

So the fundamental question is how to get the information abut the event that triggered the rule ?

**Comment by marcinczeczko** [comment]
found one the way - `Objects.keys(event)`

**Comment by IcyT** [comment]
What about using `triggeringItem.state`? (Was quite hard to find out about the triggeringItem variable)
