### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by egoist6** [openhab/openhab-js#53]
As mentioned in the other thread I'll start a new ticket about this issue which seems to be related to JSscripting.
When changing and testing JS scripts which have syntax errors, after 10-20 runs the CPU load increases to 100% and you get the following error messages:
`2021-12-29 22:12:59.868 [WARN ] [org.eclipse.jetty.server.HttpChannel] - /rest/rules/SystemReadLog
java.lang.OutOfMemoryError: Java heap space`
`2021-12-29 22:14:35.128 [WARN ] [ab.core.internal.events.EventHandler] - Dispatching event to subscriber 'org.openhab.core.io.monitor.internal.EventLogger@16f740b' takes more than 5000ms.`
`2021-12-29 22:19:26.790 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.OutOfMemoryError: Java heap space`

Let me be more precise: at least the memory leak can be reproduced with faulty JS scripts - I am not saying that the script engine is the root cause of the poblem. I just wanted to bring this to your attention.

This problem has been confirmed by a couple of users yet.

[See here](https://community.openhab.org/t/jsscripting-error-message-java-lang-outofmemoryerror-java-heap-space/130846) and
[here](https://community.openhab.org/t/javascript-memory-stability-issues/130810)

**Comment by digitaldan** [comment]
Can you open this up on https://github.com/openhab/openhab-addons/issues instead ? This would be an issue with the JS scripting engine itself, not this library, thanks!

**Comment by egoist6** [comment]
done

**Comment by digitaldan** [comment]
Thanks!
