### ISSUE TITLE
item.history.lastUpdate("serviceID") writing to log on ever call

### ISSUE THREAD

**Issue by kstuken** [openhab/openhab-js#55]
I am running OH3.2 and am using JSScript rules via files.
When calling item.history.lastUpdate("serviceID") it will write "Last Update serviceID" to log on every call, like this:

`2022-01-03 21:40:26.616 [INFO ] [org.openhab.automation.script       ] - Last Update jdbc`

**Comment by florian-h05** [comment]
This is coded here: https://github.com/openhab/openhab-js/blob/f758d62a06056b4ab96d622566601a72d641d489/items/item-history.js#L92

I think @digitaldan added this logging for debugging reasons and maybe forgot to remove it?
