### ISSUE TITLE
history.lastUpdate should return ZonedDateTime or everything else should use Date

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#59]
Consistency is the most important thing to me when it comes to usability. Everywhere else (that I've worked with the library so far) when working with date times we are working with joda-js.ZonedDateTimes (or java.time.ZonedDateTimes which is usually indistinguishable from the joda-js).

However, when pulling `lastUpdate` from `history` we get a JavaScript `Date` Object instead which works significantly differently, forcing the users to:

1. have to know and understand when they get one verses the other
2. learn two completely different ways to compare and manipulate date times

I propose we need to decide on one or the other and where ever possible always return that standard.

**Comment by rkoshak** [comment]
If it helps I've a library (I'd like to submit it as a PR when it's ready) which converts almost everything you can think of to a time.ZonedDateTime. A snippet relevant to this issue is:

```
const toDateTime = (when) => {
  var dt = null;

...

  else if(when instanceof Date) {
    logger.debug('Converting from JS Date');
    const native = time.nativeJs(when);
    const instant = time.Instant.from(native);
    dt = time.ZonedDateTime.ofInstant(instant, time.ZoneId.SYSTEM);
  }

...

  return dt;
}
```

**Comment by digitaldan** [comment]
Thanks @rkoshak !  I consider this a bug for sure, and its clear in https://github.com/openhab/openhab-js/blob/main/items/item-history.js#L183 why this is happening.

**Comment by digitaldan** [comment]
Hey @rkoshak i think this should fix this particular issue, also i am including the `@js-joda/timezone` package now, which i think may fix #54 , but i would need to test if we have to import region specific locals strings.  Let me know what you think.

**Comment by rkoshak** [comment]
I agree, this feels like a bug. This will certainly fix the issue but will be a breaking change. Do we have a good place to announce that sort of thing?

We are pretty early on here but lots of people are using it already.

I'm not sure if including timezone will be enough for #54. The docs are saying we need to import locale which I think is in a different package. But of course testing will show us one way or the other.

**Comment by digitaldan** [comment]
I'm not sure we do have a good way of communicating that users will easily see.  Do you think lots of people are using this particular method yet? I assumed it was probably still rarely used as a more minor part of a new api.

**Comment by digitaldan** [comment]
So i'm adding a new section to the readme that states breaking changes, i also use this to add in "whats new" in major releases.
