### ISSUE TITLE
utils.js missing from generated docs

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#75]
The methods in utils are quite handy. We should make sure they get into the docs too. Even if just in https://openhab.github.io/openhab-js/index.html. 

I've no idea how the docs are generated (it's on my list of things to learn) or I'd just submit a PR right now. I'll do it when I can figure it out but if it's just a quick change don't wait for me.

**Comment by florian-h05** [comment]
> Even if just in https://openhab.github.io/openhab-js/index.html.

The `index.html` is generated from `README.md`. 

After a quick look at the JSDoc, I noticed that the `utils` namespace is not in the JSDoc and after a look into `utils.js` I had the reason: the JSDoc comments are missing.

If you don't work at this now, I can have a look at this, I think I'll probably have a PR this evening.

**Comment by digitaldan** [comment]
Yeah, i actually didn't realize we exposed utils outside the library in the main index.js , would be great to have some docs around it.
