### ISSUE TITLE
Add functions to get and set full Item metadata

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#84]
The current set of functions only work with metadata values, not full metadata with a value and configuration map. This is a feature request top add functions that will get, insert, upsert, delete full metadata entries.

**Comment by digitaldan** [comment]
Have you seen #43  ?  We were discussing moving out meta data to its own namespace and then adding missing functionality .  I have not circled back to finish that up yet.

**Comment by rkoshak** [comment]
I did not see 43.  I looked at the issues but not the active PRs. I'll close this since it looks like it's being addressed.
