### ISSUE TITLE
Get Item Groups

### ISSUE THREAD

**Issue by Cossey** [openhab/openhab-js#85]
Looking at the `Item` object, it has methods for `addGroups` and `removeGroups` but there appears to be no way to get the current groups the that item is a part of.

I propose, a new property on the `Item` object called `group` with an array of group objects or names/labels.

I have contact sensors the are labelled "Is Open". The name of the actual place (ie Front Door) is on the label of the group it is a part of so it makes it a little tricky to handle in code for now.

**Comment by digitaldan** [comment]
Thank @Cossey , indeed the native/raw item has a method called `getGroupNames()` 
 i'll look at exposing this in the library. 
 
https://www.openhab.org/javadoc/latest/org/openhab/core/items/item#getGroupNames()
